### ISSUE TITLE
Clarity

### ISSUE THREAD

**Issue by vallathortense** [mdbesten/what-could-go-wrong-llm#3]
1 Opaque

**Comment by Naopod** [comment]
Can you add more details ? Because of the translation ?

**Comment by vallathortense** [comment]
translation in french

**Comment by B4dCow** [comment]
Lower the baseline knowledge needed to play the game

**Comment by B4dCow** [comment]
Maybe with images

**Comment by vallathortense** [comment]
Solved in this PR: https://github.com/mdbesten/what-could-go-wrong-llm/pull/66
