### ISSUE TITLE
New feature: modification of the abstract

### ISSUE THREAD

**Issue by lucas-hmmt** [mdbesten/what-could-go-wrong-llm#59]
The current abstract section in the readme corresponds to the old iteration of the game about autonomous vehicles. Let's adapt it to the topic of AI and LLMs:

"While artificial intelligence and large language models (LLMs) hold the promise of revolutionizing various sectors of our society, they also come with their own set of challenges and potential pitfalls. In this workshop, our aim is to encourage discussions around the possible negative impacts of AI and LLMs to bring to light issues that need to be addressed during the development phase rather than post-deployment. This discussion will be sparked by reviewing participant position statements and through group discussions facilitated by a card game titled "What Could Go Wrong?" Our objective is to weigh the benefits of AI and LLMs—such as enhancing efficiency, fostering innovation, and facilitating problem-solving—against the possible drawbacks. By uncovering potential harms and disadvantages, the workshop participants, and the AI research and development community at large, can design more thoughtful and responsible solutions."

**Comment by mdbesten** [comment]
The abstract belongs to the paper in which the game was first proposed. 
I'd rather you modify the introductory paragraphs in the IREN-branch to explain its goal to focus the game on issues that can go wrong with or within online communities.
